<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

**Group 6**

Students name in this Group:

1. Ahmed Ali
2. Nichapat Boonprasertsri
3. Anuphap Chansatit
4. Karthikeyan Jeyabalasuntharam
5. Yat Chit Law
6. Halari Shanpru
7. Vitchaya Siripoppohn
8. Chotiros Srisiam


In [10]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

a = np.array([[5, 2, 3],
            [6, 1, 3],
            [2, 4, 1]])
print("Matrix A = \n", a)

b = a[0:2, 0:2]
print("Matrix B = \n", b)

c = a[1:3, 1:3]
print("Matrix C = \n", c)

Matrix A = 
 [[5 2 3]
 [6 1 3]
 [2 4 1]]
Matrix B = 
 [[5 2]
 [6 1]]
Matrix C = 
 [[1 3]
 [4 1]]
